// <auto-generated />
namespace MyNote.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _4_EventAndUserReferenceEdited : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_4_EventAndUserReferenceEdited));
        
        string IMigrationMetadata.Id
        {
            get { return "201703031701321_4_EventAndUserReferenceEdited"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
